<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-17 08:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
=======
# Generated by Django 5.0.2 on 2024-03-17 09:48

import django.contrib.auth.models
import django.utils.timezone
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_photo/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='brand_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
=======
                ('image', models.ImageField(upload_to='brand_photo/')),
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to='partner_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='New_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_photo/')),
                ('title', models.CharField(max_length=55)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_photo/')),
                ('title', models.CharField(max_length=55)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
            name='Shop_colloection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_picture/')),
                ('short_text', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Treding_ats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tredign_photo/')),
                ('title', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
<<<<<<< HEAD
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
=======
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
<<<<<<< HEAD
=======
                ('username', models.CharField(max_length=55, verbose_name='Isim familyasi')),
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
                ('phone_number', models.CharField(max_length=150, unique=True, verbose_name='Telefon Raqam')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchi',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_photo/')),
                ('title', models.CharField(max_length=55)),
                ('price', models.IntegerField(default=0)),
                ('product_info', models.TextField(blank=True, null=True)),
                ('is_banner', models.BooleanField(default=False)),
                ('banner_title', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_text', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_collections', models.BooleanField(default=False)),
                ('featured_product', models.BooleanField(default=False)),
                ('is_advert', models.BooleanField(default=False)),
                ('advert_text', models.CharField(blank=True, max_length=50, null=True)),
                ('new_product', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
=======
>>>>>>> f39bb3d53b81389995578f43d77343fdfb7ae42f
    ]
